"""
POST /report              — Generate Doctor Handoff Report
GET  /report/{session_id} — Retrieve latest report for a session
PUT  /report/{report_id}  — Update vital flags or doctor notes on a report

Day 5 enhancements:
- ICD-10 code lookup for differential diagnoses
- Structured conversation timeline for PDF rendering
- Urgency-level-appropriate vital flags
- Confidence band and model source in triage decision
"""
import uuid
from datetime import datetime, timezone
from fastapi import APIRouter, Request, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from pdf_generator import generate_pdf

router = APIRouter()


class ReportRequest(BaseModel):
    session_id: str


class UpdateReportRequest(BaseModel):
    vital_flags: list[str] | None = None
    doctor_notes: str | None = None
    report_pdf_url: str | None = None


# ── POST — generate report ─────────────────────────────────────────────────────
@router.post("", summary="Generate Doctor Handoff Report from a completed session")
async def generate_report(req: ReportRequest, request: Request):
    db = request.app.state.db
    session = await db.patient_sessions.find_one({"session_id": req.session_id})
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if not session.get("triage_result"):
        raise HTTPException(status_code=400, detail="Run /triage before generating a report")

    triage = session["triage_result"]
    all_entities = [
        e for turn in session.get("conversation", [])
        for e in turn.get("extracted_entities", [])
    ]
    unique_symptoms = list({e["text"]: e for e in all_entities}.values())

    report = {
        "report_id":    str(uuid.uuid4()),
        "session_id":   req.session_id,
        "generated_at": datetime.now(timezone.utc),
        "patient_summary": session.get("patient_info", {}),
        "chief_complaint": session["conversation"][0]["user_input"] if session.get("conversation") else "",
        "extracted_symptoms": [
            {"symptom": e["text"], "severity": None, "duration": None}
            for e in unique_symptoms
        ],
        "differential_diagnosis": [
            {
                "condition":   c,
                "probability": round(triage["confidence"] * 0.9 ** i, 2),
                "icd10_code":  _ICD10_MAP.get(c),
                "source":      "rule_engine" if i == 0 else "neo4j",
            }
            for i, c in enumerate(triage.get("possible_conditions", []))
        ],
        "triage_decision": {
            "urgency_level":      triage["urgency_level"],
            "recommended_action": triage["recommended_action"],
            "urgency_score":      triage.get("urgency_score", 0),
            "confidence":         triage.get("confidence", 0),
            "model_source":       triage.get("source", "rule_engine"),
            "assigned_at":        datetime.now(timezone.utc),
        },
        "conversation_timeline": _build_timeline(session.get("conversation", [])),
        "vital_flags":    _vital_flags(triage["urgency_level"]),
        "doctor_notes":   None,
        "report_pdf_url": None,
        "disclaimer": (
            "This report was generated by MedTriage AI v1.0 using BioBERT NER and a "
            "medical knowledge graph. It is decision support ONLY and does NOT "
            "constitute a medical diagnosis. All clinical decisions must be made by a "
            "licensed physician. If this is an emergency, call 911 or 108 immediately."
        ),
    }

    await db.handoff_reports.insert_one(report)
    report.pop("_id", None)
    return report


# ── GET — retrieve latest report ───────────────────────────────────────────────
@router.get("/{session_id}", summary="Get latest handoff report for a session")
async def get_report(session_id: str, request: Request):
    db = request.app.state.db
    report = await db.handoff_reports.find_one(
        {"session_id": session_id},
        sort=[("generated_at", -1)],
    )
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    report.pop("_id", None)
    return report


# ── GET — download PDF ────────────────────────────────────────────────────────
@router.get("/{session_id}/pdf", summary="Download handoff report as PDF")
async def download_pdf(session_id: str, request: Request):
    db = request.app.state.db
    report = await db.handoff_reports.find_one(
        {"session_id": session_id},
        sort=[("generated_at", -1)],
    )
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    report.pop("_id", None)
    pdf_bytes = generate_pdf(report)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=report_{session_id[:8]}.pdf"},
    )


# ── PUT — update vital flags / doctor notes ────────────────────────────────────
@router.put("/{report_id}", summary="Update vital flags or doctor notes on a report")
async def update_report(report_id: str, req: UpdateReportRequest, request: Request):
    db = request.app.state.db
    report = await db.handoff_reports.find_one({"report_id": report_id})
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    updates = {k: v for k, v in req.model_dump().items() if v is not None}
    if not updates:
        raise HTTPException(status_code=400, detail="No fields to update")

    updates["updated_at"] = datetime.now(timezone.utc)
    await db.handoff_reports.update_one({"report_id": report_id}, {"$set": updates})

    return {
        "report_id": report_id,
        "updated": list(updates.keys()),
        "message": "Report updated successfully.",
    }


# ── Internal helpers ───────────────────────────────────────────────────────────

_ICD10_MAP: dict[str, str] = {
    "Myocardial Infarction":       "I21.9",
    "Angina":                       "I20.9",
    "Unstable Angina":              "I20.0",
    "Aortic Dissection":            "I71.0",
    "Pulmonary Embolism":           "I26.9",
    "Heart Failure":                "I50.9",
    "Ischemic Stroke":              "I63.9",
    "Hemorrhagic Stroke":           "I61.9",
    "TIA":                          "G45.9",
    "Subarachnoid Hemorrhage":      "I60.9",
    "Meningitis":                   "G03.9",
    "Bacterial Meningitis":         "G00.9",
    "Sepsis":                       "A41.9",
    "Appendicitis":                 "K35.9",
    "Deep Vein Thrombosis":         "I82.9",
    "Asthma Attack":                "J45.901",
    "Pneumonia":                    "J18.9",
    "COVID-19":                     "U07.1",
    "Influenza":                    "J11.1",
    "Migraine":                     "G43.909",
    "Tension Headache":             "G44.209",
    "Gastroenteritis":              "K52.9",
    "UTI":                          "N39.0",
    "Kidney Stone":                 "N20.0",
    "Vertigo":                      "H81.39",
    "Hypoglycemia":                 "E11.641",
    "Upper GI Bleed":               "K92.2",
    "Cardiac Arrhythmia":           "I49.9",
    "Atrial Fibrillation":          "I48.91",
    "Ventricular Tachycardia":      "I47.2",
    "Psychiatric Emergency":        "F99",
    "Ruptured Aortic Aneurysm":     "I71.4",
    "Meningococcemia":              "A39.4",
    "Epiglottitis":                 "J05.10",
    "Anaphylaxis":                  "T78.2XXA",
    "Common Cold":                  "J00",
    "Strep Throat":                 "J02.0",
}


def _vital_flags(urgency: str) -> list[str]:
    """Return urgency-level-appropriate vital flags for the receiving physician."""
    base = [
        "AI triage confidence may vary — clinical judgment and examination must override AI assessment.",
        "MedTriage AI is decision support only; confirmatory investigations are mandatory.",
    ]
    if urgency == "CRITICAL":
        return [
            "⚠ Requires IMMEDIATE physician assessment — life-threatening condition suspected.",
            "Do NOT delay treatment while awaiting definitive test results.",
            "Activate rapid-response / resuscitation team as per local protocol.",
            "Ensure IV access, continuous cardiac monitoring, and SpO₂ tracking.",
            "Time-sensitive — every minute of delay worsens outcome.",
        ] + base
    elif urgency == "HIGH":
        return [
            "⚠ Requires urgent physician review within 30 minutes.",
            "Conduct focused history, physical examination, and targeted investigations.",
            "Consider ECG, blood panels (troponin, CBC, CMP), and imaging as indicated.",
            "Reassess triage level after initial evaluation.",
        ] + base
    elif urgency == "MEDIUM":
        return [
            "Patient should be seen by a physician within 4 hours.",
            "Monitor for symptom escalation and reassess triage level if needed.",
            "Provide patient with written instructions on warning signs requiring ER visit.",
        ] + base
    else:
        return [
            "Non-urgent — schedule follow-up with GP within 48–72 hours.",
            "Advise patient to return immediately if symptoms worsen or new symptoms develop.",
        ] + base


def _build_timeline(conversation: list) -> list[dict]:
    """Convert raw conversation turns into a structured timeline for PDF rendering."""
    timeline = []
    for turn in conversation:
        ts = turn.get("timestamp")
        if hasattr(ts, "isoformat"):
            ts_str = ts.isoformat()
        else:
            ts_str = str(ts) if ts else datetime.now(timezone.utc).isoformat()

        # Patient turn
        if turn.get("user_input"):
            timeline.append({
                "timestamp": ts_str,
                "speaker": "patient",
                "content": turn["user_input"],
                "symptoms_extracted": turn.get("symptoms_this_turn", []),
            })

        # AI turn
        if turn.get("bot_reply"):
            timeline.append({
                "timestamp": ts_str,
                "speaker": "ai",
                "content": turn["bot_reply"],
                "entities": [e.get("text", "") for e in turn.get("extracted_entities", [])],
            })

    return timeline
