from pdf_generator import generate_pdf
from datetime import datetime, timezone
import os

report = {
    "report_id": "test-1234-abcd-5678-efgh-ijkl",
    "session_id": "sess-abcd-1234-efgh",
    "generated_at": datetime.now(timezone.utc),
    "patient_summary": {"age": 45, "sex": "Male", "known_conditions": ["Hypertension", "Diabetes"]},
    "chief_complaint": "I have chest pain and shortness of breath and I am sweating",
    "extracted_symptoms": [
        {"symptom": "chest pain"}, {"symptom": "shortness of breath"},
        {"symptom": "sweating"},   {"symptom": "dizziness"},
        {"symptom": "palpitations"}, {"symptom": "fatigue"},
    ],
    "differential_diagnosis": [
        {"condition": "Myocardial Infarction", "probability": 0.92, "icd10_code": "I21.9", "source": "rule_engine"},
        {"condition": "Pulmonary Embolism",    "probability": 0.75, "icd10_code": "I26.9", "source": "neo4j"},
        {"condition": "Angina",                "probability": 0.60, "icd10_code": "I20.9", "source": "neo4j"},
        {"condition": "Aortic Dissection",     "probability": 0.45, "icd10_code": "I71.0", "source": "neo4j"},
    ],
    "triage_decision": {
        "urgency_level": "CRITICAL", "urgency_score": 92, "confidence": 0.92,
        "recommended_action": "Call 108 immediately", "model_source": "rule_engine",
    },
    "vital_flags": [
        "Requires IMMEDIATE physician assessment - life-threatening condition suspected.",
        "Do NOT delay treatment while awaiting definitive test results.",
        "Activate rapid-response / resuscitation team as per local protocol.",
        "AI triage confidence may vary - clinical judgment must override AI assessment.",
    ],
    "disclaimer": "This report was generated by MedTriage AI v1.0 using BioBERT NER and a medical knowledge graph. It is decision support ONLY and does NOT constitute a medical diagnosis.",
}

pdf = generate_pdf(report)
path = os.path.join(os.path.dirname(__file__), "sample_report.pdf")
with open(path, "wb") as f:
    f.write(pdf)
print(f"PDF generated: {len(pdf)} bytes -> {path}")
